### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Artanis** [Maselkov/GW2RPC#30] opened 2022-10-05 23:01 UTC
Whenever I launch the application, it crashes. This crash occurs on both the most recent version on the website (v2.51?) and in 2.52-b1.

Log:
```
2022-10-05 15:41:43,685:CRITICAL:root: GW2RPC has crashed
Traceback (most recent call last):
  File "gw2rpc\gw2rpc.py", line 734, in main_loop
  File "gw2rpc\lib\discordsdk\discord.py", line 99, in run_callbacks
gw2rpc.lib.discordsdk.exception.internal_error: result 4
```

Code involved in the trace back:

https://github.com/Maselkov/GW2RPC/blob/379ed5f52f8d433134bf87d1018a1ff52e158560/gw2rpc/gw2rpc.py#L732-L745
https://github.com/Maselkov/GW2RPC/blob/379ed5f52f8d433134bf87d1018a1ff52e158560/gw2rpc/lib/discordsdk/discord.py#L93-L99

**Comment by n1tr0-5urf3r** [comment] 2022-10-06 04:19
Thanks for the report! 
There are currently some issues with the SDK connection to Discord I think.
It seems like it does not happen to all users, but many other people have the same problem with other games.
So far there is no solution known as discord staff was not able to reproduce it, but it's being discussed on the Developers Discord.

You could try with another Discord account as it seems to be tied to that, but that's no solution of course. Must be some Discord internal issue. I hope it will be fixed soon as I'm not able to use GW2RPC at the moment too.

**Comment by n1tr0-5urf3r** [comment] 2022-10-20 16:48
> Whenever I launch the application, it crashes. This crash occurs on both the most recent version on the website (v2.51?) and in 2.52-b1.
> 
> Log:
> 
> ```
> 2022-10-05 15:41:43,685:CRITICAL:root: GW2RPC has crashed
> Traceback (most recent call last):
>   File "gw2rpc\gw2rpc.py", line 734, in main_loop
>   File "gw2rpc\lib\discordsdk\discord.py", line 99, in run_callbacks
> gw2rpc.lib.discordsdk.exception.internal_error: result 4
> ```
> 
> Code involved in the trace back:
> 
> https://github.com/Maselkov/GW2RPC/blob/379ed5f52f8d433134bf87d1018a1ff52e158560/gw2rpc/gw2rpc.py#L732-L745
> 
> https://github.com/Maselkov/GW2RPC/blob/379ed5f52f8d433134bf87d1018a1ff52e158560/gw2rpc/lib/discordsdk/discord.py#L93-L99

It finally got fixed! It was  bug related to ppl who had Discord Nitro and dont have it anymore, or created their account back in June 2017.
Updating discord should do the trick, the working release for me is Stable 153350 (7902cab).

**Closed by n1tr0-5urf3r** 2022-10-20 16:48 UTC
