### ISSUE TITLE
Installer always installs to `C:\Program Files\Guild Wars 2\addons\GW2RPC\`

### ISSUE THREAD

**Issue by Fishrock123** [Maselkov/GW2RPC#33] opened 2023-09-02 18:03 UTC
The installer always installs to `C:\Program Files\Guild Wars 2\addons\GW2RPC\` even if you tell it otherwise.

My game is located at `Z:\Games\Guild Wars 2\addons\GW2RPC\` for a bunch of reasons.

**Comment by n1tr0-5urf3r** [comment] 2023-09-02 20:17
That's definitely not intended, thanks for reporting. I will investigate the issue, for now you can simply copy over the folder from C:\ to your GW2 install directory.

**Comment by Fishrock123** [comment] 2023-09-02 21:14
Yep, that’s what I ended up doing after several confusing attempts haha

**Comment by Fishrock123** [comment] 2023-09-02 21:18
I don’t know `.nsi` well, but I think the problem may be at https://github.com/Maselkov/GW2RPC/blob/master/dist/installer.nsi#L129 - should that `$2` be `$INSTDIR`?

**Comment by n1tr0-5urf3r** [comment] 2023-09-03 08:20
I think the issue is that the installer uses the GW2 installation path from the registry.
Did you initially install the game on your C:\ drive and manually copied it over to your Z:\ drive?
Can you check the registry value at HKEY_LOCAL_MACHINE\SOFTWARE\ArenaNet\Guild Wars 2\Path for me?

**Comment by n1tr0-5urf3r** [comment] 2023-09-03 08:47
Nonetheless, the behavior of the installer to ignore the specified path if it detecs the GW2 installation path was not intended.
I think I've found the issue, it should be fixed now :) 
I created a new release for this.

**Closed** 2023-12-23 09:50 UTC
Labels: bug
